url = https://rahulshettyacademy.com/seleniumPractise
products = Brocolli,Cauliflower,Beetroot,Cucumber,Carrot,Tomato,Beans,Brinjal,Capsicum,Strawberry,Water Melon,Almonds,Pista,Nuts Mixture,Cashews,Walnuts
product = apple
keyword = test
quantity = 15
discountCode = rahulshettyacademy
country = Romania
pageSize = 10
monthYear = August 2030
day = 1